# cms

production: &production
  # Static files
  serve_static_pages: true

  # HTML editor (ckeditor, tinymce)
  html_editor: ckeditor

  # Link Check Ajax URL
  link_check_url: /.cms/link_check/check.json

  # Correct Page's HTML When Saving
  auto_correct_page_html: false

  # Google Map API Center Location
  map_center:
    - 36.204824
    - 138.252924

test:
  <<: *production

development:
  <<: *production
