# cms

production: &production
  # StyleSheets on gws pages.
  stylesheets: []

  # JavaScripts on gws pages.
  javascripts: []

  # Static files
  serve_static_pages: true

  # HTML editor (ckeditor, tinymce, markdown)
  html_editor: ckeditor

  # CKEditor setting
  ckeditor:
    # base options
    options:
      allowedContent: true
      height: 360px
      templates: 'shirasagi'
      extraPlugins:
        - templates
        - justify
        - panelbutton
        - colorbutton
        - font
      removeButtons: 'Underline,Subscript,Superscript,Font,BGColor,Source'
      fontSize_sizes: '60%/60%;70%/70%;80%/80%;90%/90%;100%/100%;110%/110%;120%/120%;130%/130%;140%/140%;150%/150%;160%/160%;170%/170%;180%/180%;190%/190%;200%/200%;'
      colorButton_colors: 'Maroon/800000,SaddleBrown/8B4513,DarkSlateGray/2F4F4F,Teal/008080,Navy/000080,Indigo/4B0082,DarkGray/696969,FireBrick/B22222,Brown/A52A2A,GoldenRod/DAA520,DarkGreen/006400,MediumBlue/0000CD,Purple/800080,Gray/808080,Red/EE0000,Green/008000,Blue/0000FF'
    # readonly options override base options when mode is readonly
    readonly_options:
      readOnly: true
      removePlugins:
        - toolbar
    # public-side options override base options when mode is public-side
    public_side_options:
      templates:
    # advanced options override base options when mode is advanced
    advanced_options:
      removeButtons: 'Underline,Subscript,Superscript,Font,BGColor'
    # ckeditor's javascripts options
    javascripts:
      - /assets/js/ckeditor/ckeditor.js
      - /assets/js/ckeditor/adapters/jquery.js

  # Link Check Ajax URL
  link_check_url: /.cms/link_check/check.json

  # Correct Page's HTML When Saving
  auto_correct_page_html: false

  editor_template_thumb: "/assets/img/editor-template.png"

  # Skip login for preview
  remote_preview: false

  # Session Lifetime in seconds
  session_lifetime: 1800

test:
  <<: *production

development:
  <<: *production
