production: &production
  # smtp or sendmail
  delivery_method: sendmail

  # smtp settings
  address: localhost
  port: 25
  domain: localhost
  user_name:
  password:
  authentication:

  # sendmail settings
  location:
  arguments:

  # message settings
  default_from: noreply@example.jp
  default_charset: utf-8

test:
  delivery_method: test
  default_from: noreply@example.jp
  default_charset: utf-8

development:
  <<: *production
  delivery_method: file
